*CLS
*ESE
*ESR?
*IDN?
*OPC?
*RCL
*RST
*SAV
*SRE
*STB?
ABOR(t)
CONF(igure):BEEP(er)
CONF(igure):REM(ote)
CONF(igure):OUTP(ut)
CONF(igure):FOLD(back)
CONF(igure):FOLDT
CONF(igure):APGVS(et)
CONF(igure):AOGVM(eas)
CONF(igure):APGIS(et)
CONF(igure):APGIM(eas)
CONF(igure):AVG:TIMES
CONF(igure):AVG:METH(od)
CONF(igure):BRIG(htness)
CONF(igure):MSTSLV:ID
CONF(igure):MSTSLV:PARSER
CONF(igure):MSTSLV:NUMSLV
CONF(igure):MSTSLV
CONF(igure):INH(ibit):PULL
CONF(igure):INTERLOCK
CONF(igure):INTERLOCK:PULL
CONF(igure):EXTON
CONF(igure):EXTON:PULL
SOUR(ce):VOLT(age)
SOUR(ce):VOLT(age):LIM(it):{HIGH/LOW}
SOUR(ce):VOLT(age):PROT(ect):{HIGH}
SOUR(ce):VOLT(age):SLEW
SOUR(ce):CURR(ent)
SOUR(ce):CURR(ent):LIM(it):{HIGH/LOW}
SOUR(ce):CURR(ent):PROT(ect):{HIGH}
SOUR(ce):CURR(ent):SLEW
SOUR(ce):CURR(ent):SLEWINF
SOUR(ce):POW(er):PROT(ect):HIGH
SOUR(ce):DCON:{RISE/FALL}
FETC(h):VOLT(age)?
FETC(h):CURR(ent)?
FETC(h):POW(er)?
FETC(h):STAT(us)?
MEAS(ure):VOLT(age)?
MEAS(ure):CURR(ent)?
MEAS(ure):POW(er)?
PROG(ram):SEL(ected)
PROG(ram):LINK
PROG(ram):COUNT
PROG(ram):RUN
PROG(ram):SAVE
PROG(ram):SEQ(uence):SEL(ected)
PROG(ram):SEQ(uence):TYPE
PROG(ram):SEQ(uence):VOLT(age)
PROG(ram):SEQ(uence):VOLT(age):SLEW
PROG(ram):SEQ(uence):CURR(ent)
PROG(ram):SEQ(uence):CURR(ent):SLEW
PROG(ram):SEQ(uence):CURR(ent):SLEWINF
PROG(ram):SEQ(uence):TIME
PROG(ram):CLEAR
PROG(ram):ADD
PROG(ram):MAX?
PROG(ram):SEQ(uence)
PROG(ram):MODE
PROG(ram):STEP:STARTV
PROG(ram):STEP:ENDV
PROG(ram):STEP:TIME
SYST(em):ERR(or)?